# Generated by Django 3.1.5 on 2021-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sms_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='01f83036-8560-4344-8c35-31ce8bfd', max_length=255),
        ),
    ]
