# Generated by Django 3.1.5 on 2021-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type_c',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Insurance company', 'Insurance company'), ('Medtravel company', 'Medtravel company'), ('Pharmaceutical company', 'Pharmaceutical company'), ('Charity foundation', 'Charity foundation')], default='Clinic', max_length=64),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default='2021-02-01 00:00'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default='2021-02-01 00:00'),
        ),
    ]
