# Generated by Django 3.1.5 on 2021-01-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32, null=True, unique=True)),
                ('phone', models.CharField(max_length=16, null=True, unique=True)),
                ('sms_code', models.CharField(max_length=4, null=True)),
                ('cover_name', models.CharField(max_length=64, null=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('middle_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('language', models.CharField(choices=[('en', 'en'), ('de', 'de'), ('fr', 'fr'), ('sp', 'sp'), ('ru', 'ru'), ('pt', 'pt'), ('it', 'it'), ('ja', 'ja'), ('ko', 'ko'), ('zh', 'zh'), ('tr', 'tr')], default='en', max_length=2)),
                ('country', models.CharField(default='Russia', max_length=64)),
                ('city', models.CharField(default='Moscow', max_length=64)),
                ('step', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='anonym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='secure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default='2021-01-29 00:00'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='source.profile'),
        ),
    ]
