# Generated by Django 3.1.5 on 2021-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20210201_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default='2021-02-03 19:27'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default='2021-02-03 00:00'),
        ),
    ]
