# Generated by Django 3.1.5 on 2021-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20210203_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default='2021-02-08 21:10'),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default='2021-02-08 21:10'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default='2021-02-08 21:10'),
        ),
    ]
