# Generated by Django 3.1.5 on 2021-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20210208_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default='2021-02-08 21:33'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default='2021-02-08 21:33'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default='2021-02-08 21:33'),
        ),
    ]
