# Generated by Django 3.1.5 on 2021-02-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_auto_20210211_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default='2021-02-11 21:41'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default='2021-02-11 21:41'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default='2021-02-11 21:41'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
