# Generated by Django 3.1.5 on 2021-02-14 15:03

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_auto_20210211_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('let', models.BooleanField(default=True)),
                ('default_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
            options={
                'db_table': 'reference_book',
            },
        ),
        migrations.CreateModel(
            name='UserChoicesRB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('rb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.referencebook')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='QuestionBlock',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
        migrations.DeleteModel(
            name='Questionnarie',
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 18, 3, 36, 214555)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 18, 3, 36, 207719)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 18, 3, 36, 207719)),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
