# Generated by Django 3.1.5 on 2021-02-14 16:26

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_auto_20210214_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('question_group_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('question_block_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('role_of_author', models.CharField(default='anonym', max_length=256)),
                ('status', models.CharField(choices=[('public', 'public'), ('custom', 'custom'), ('draft', 'draft')], max_length=256)),
                ('question_type', models.CharField(choices=[('table', 'table'), ('upload_link', 'upload_link'), ('upload_file', 'upload_file'), ('select_list', 'select_list'), ('date', 'date'), ('text', 'text'), ('numeric_with_measurement_unit', 'numeric_with_measurement_unit'), ('numeric', 'numeric'), ('toggle', 'toggle')], max_length=256)),
                ('data_type', models.CharField(choices=[('medical', 'medical'), ('non-medical', 'non-medical'), ('clarifying', 'clarifying')], max_length=256)),
                ('question_value', models.TextField()),
                ('question_label', models.TextField(null=True)),
                ('prompt_text', models.TextField(null=True)),
                ('required_answer', models.BooleanField(default=False)),
                ('allow_multiple_answer', models.BooleanField(default=False)),
                ('historically_tracked', models.BooleanField(default=False)),
                ('parent_question_id', models.IntegerField(null=True)),
                ('answer_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None)),
                ('multiple_selection', models.BooleanField(default=False)),
                ('min_additions', models.IntegerField(null=True)),
                ('max_additions', models.IntegerField(null=True)),
                ('min_symbols', models.IntegerField(null=True)),
                ('max_symbols', models.IntegerField(null=True)),
                ('rows_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='2', max_length=256)),
                ('keywords_recognize', models.BooleanField(default=False)),
                ('date_type', models.CharField(choices=[('one', 'one'), ('start_and_end', 'start_and_end')], max_length=256, null=True)),
                ('allow_current_future_date', models.BooleanField(default=False)),
                ('allow_approximate_date', models.BooleanField(default=False)),
                ('measurement_units', models.CharField(max_length=128, null=True)),
                ('measurement_unit_by_default', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('question_group_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'db_table': 'question_block',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'question_group',
            },
        ),
        migrations.CreateModel(
            name='Questionnarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('question_group_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('question_block_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('chapter_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'db_table': 'questionnarie',
            },
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 26, 38, 481156)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 26, 38, 475297)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 26, 38, 475297)),
        ),
        migrations.CreateModel(
            name='ChoiceMeasurment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='source.question')),
            ],
            options={
                'db_table': 'choice_measurment',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='source.question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
