# Generated by Django 3.1.5 on 2021-02-14 16:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_auto_20210214_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemeasurment',
            name='question',
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 47, 30, 246781)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 47, 30, 238969)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 47, 30, 238969)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_additions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_symbols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='measurement_unit_by_default',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='measurement_units',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_additions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_symbols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
