# Generated by Django 3.1.5 on 2021-02-15 18:19

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_auto_20210214_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceAgeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_age_groups',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_attachment',
            },
        ),
        migrations.CreateModel(
            name='ChoiceBioMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_bio_market',
            },
        ),
        migrations.CreateModel(
            name='ChoiceDefaultBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_default_block',
            },
        ),
        migrations.CreateModel(
            name='ChoiceDefaultChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_default_chapter',
            },
        ),
        migrations.CreateModel(
            name='ChoiceDestinationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_destination_block',
            },
        ),
        migrations.CreateModel(
            name='ChoiceDestinationChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_destination_chapter',
            },
        ),
        migrations.CreateModel(
            name='ChoiceGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_gender',
            },
        ),
        migrations.CreateModel(
            name='ChoiceHealthStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_health_status',
            },
        ),
        migrations.CreateModel(
            name='ChoiceMeasurmentDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_measurment_default',
            },
        ),
        migrations.CreateModel(
            name='ChoiceMeddataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'choice_meddata_type',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='additional_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='question',
            name='age_groups',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_impact_to_health_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_formats',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='biomarket',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_table',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='default_block',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='default_chapter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='destination_blocks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='destination_chapters',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='divider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='influence_to_additional_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='meddata_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='refbook_for_selectlist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 19, 23, 826172)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 19, 23, 818359)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 19, 23, 818359)),
        ),
        migrations.AlterField(
            model_name='question',
            name='measurement_units',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
